# Generated by Django 3.1 on 2020-08-07 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20200807_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pageinfo',
            new_name='pageInfo',
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
