# Generated by Django 3.1 on 2020-08-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200807_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='pageinfo',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=125),
        ),
    ]
